/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventaspc;

import javax.swing.JDialog;
import ventaspc.gui.modulos.PrincipalPanel;
import ventaspc.gui.VentanaPC;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan
 */
public class LoginDialog extends javax.swing.JPanel {
    private JDialog login;
    private Sistema sistema;
    /**
     * Creates new form LoginPanel
     * Panel que pasará a ser el contentPane del diálogo login en la clase Sistema
     */
    public LoginDialog(JDialog login, Sistema sistema) {
        this.login = login;
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnUsuariosAcceso = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(320, 260));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña: ");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentasPClogo.png"))); // NOI18N

        btnUsuariosAcceso.setText("Usuarios con acceso");
        btnUsuariosAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosAccesoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEntrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnUsuariosAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnEntrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuariosAcceso)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        //La clase Empleado cumple la función de crear usuarios, con su
        //contraseña y el puesto de trabajo que tienen. Esto recorrerá
        //el ArrayList de empleados (o usuarios) en la clase Empresa y
        //verificará si el usuario, con la debida contraseña se encuentra.
        // for (int i=0; i<sistema.getEmpresa().getEmpleados().size(); i++){
            //Verificación del usuario y contraseña para entrar al sistema
            // if ((txtUsuario.getText().equals(sistema.getEmpresa().getEmpleados().get(i).getUsuario()) && txtContrasena.getText().equals(sistema.getEmpresa().getEmpleados().get(i).getContrasena()))){
                JOptionPane.showMessageDialog(this,"Bienvenido " + txtUsuario.getText());
                login.dispose();//El diálogo se cierra tras haber entrado correctamente
                return;
            // s}
        //} 
        // JOptionPane.showMessageDialog(this,"Datos de ingreso incorrectos");
        
    }//GEN-LAST:event_btnEntrarActionPerformed
            
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);//Cerrar el programa
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnUsuariosAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosAccesoActionPerformed
        // TODO add your handling code here:
        //En el string usuarios, se mostrarán los nombres de todos aquellos
        //que tienen acceso al sistema, y para ello se recorre el ArrayList de
        //empleados en la clase Empresa
        String usuarios = "";
        for (int i=0; i<sistema.getEmpresa().getEmpleados().size(); i++)
            usuarios = usuarios + sistema.getEmpresa().getEmpleados().get(i).getUsuario() + "\n";
        JOptionPane.showMessageDialog(this,
        "Usuarios con acceso al sistema:\n" + usuarios,
        "Usuarios",
        JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnUsuariosAccesoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuariosAcceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
