/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventaspc.gui.modulos;

import ventaspc.empresa.posesiones.Cliente;
import java.awt.BorderLayout;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import ventaspc.*;
import ventaspc.factura.Factura;

/**
 *
 * @author Ivan
 */
//Clase que funciona como panel principal. Muestra los diferentes botones para
//accesar a los diferentes paneles del programa
public class PrincipalPanel extends PanelBase {//Hereda de PanelBase
    /**
     * Creates new form PrincipalPanel
     */
    public PrincipalPanel(Sistema sistema) {
        super(sistema);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevoCliente = new javax.swing.JButton();
        btnVerPC = new javax.swing.JButton();
        btnComprarPC = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnVerVentas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarClientes = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        btnRegistrarUsuarios = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(380, 445));

        btnNuevoCliente.setBackground(new java.awt.Color(255, 0, 51));
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuinicio/client.png"))); // NOI18N
        btnNuevoCliente.setText("Registro de un nuevo cliente");
        btnNuevoCliente.setBorder(new javax.swing.border.MatteBorder(null));
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnVerPC.setBackground(new java.awt.Color(102, 102, 255));
        btnVerPC.setForeground(new java.awt.Color(255, 255, 255));
        btnVerPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuinicio/computer_see.png"))); // NOI18N
        btnVerPC.setText("Ver computadoras en venta");
        btnVerPC.setBorder(new javax.swing.border.MatteBorder(null));
        btnVerPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPCActionPerformed(evt);
            }
        });

        btnComprarPC.setBackground(new java.awt.Color(255, 51, 255));
        btnComprarPC.setForeground(new java.awt.Color(255, 255, 255));
        btnComprarPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuinicio/purchase.png"))); // NOI18N
        btnComprarPC.setText("Compra de una computadora");
        btnComprarPC.setBorder(new javax.swing.border.MatteBorder(null));
        btnComprarPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarPCActionPerformed(evt);
            }
        });

        btnRegistro.setBackground(new java.awt.Color(51, 204, 0));
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuinicio/register.png"))); // NOI18N
        btnRegistro.setText("Registro de computadoras");
        btnRegistro.setBorder(new javax.swing.border.MatteBorder(null));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnVerVentas.setBackground(new java.awt.Color(153, 153, 0));
        btnVerVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuinicio/sale-icon.png"))); // NOI18N
        btnVerVentas.setText("Mostrar ventas realizadas");
        btnVerVentas.setBorder(new javax.swing.border.MatteBorder(null));
        btnVerVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerVentasActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentasPClogo.png"))); // NOI18N

        btnMostrarClientes.setBackground(new java.awt.Color(255, 153, 0));
        btnMostrarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuinicio/verClientes.png"))); // NOI18N
        btnMostrarClientes.setText("Mostrar todos los clientes");
        btnMostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarClientesActionPerformed(evt);
            }
        });

        btnFactura.setBackground(new java.awt.Color(51, 204, 255));
        btnFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuinicio/factura.png"))); // NOI18N
        btnFactura.setText("Generación de factura (pdf)");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        btnRegistrarUsuarios.setBackground(new java.awt.Color(0, 102, 102));
        btnRegistrarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuinicio/users.png"))); // NOI18N
        btnRegistrarUsuarios.setText("Registro de un usuario");
        btnRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComprarPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrarClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerPC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprarPC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerPC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //Eventos de cada uno de los botones
    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_NUEVOCLIENTE);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnVerPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPCActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_COMPUTADORASTABLA);
    }//GEN-LAST:event_btnVerPCActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_REGISTROCOMPUTADORA);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnComprarPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarPCActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_COMPRACOMPUTADORA);
    }//GEN-LAST:event_btnComprarPCActionPerformed

    private void btnVerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerVentasActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_VENTASTABLA);
    }//GEN-LAST:event_btnVerVentasActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_FACTURATABLA);
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnMostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarClientesActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_CLIENTESTABLA);
    }//GEN-LAST:event_btnMostrarClientesActionPerformed

    private void btnRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuariosActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_REGISTROUSUARIO);
    }//GEN-LAST:event_btnRegistrarUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarPC;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnMostrarClientes;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnRegistrarUsuarios;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnVerPC;
    private javax.swing.JButton btnVerVentas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
