/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventaspc.gui.modulos.dialogos;

import javax.swing.JButton;
import ventaspc.gui.modulos.PrincipalPanel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import ventaspc.Sistema;
import ventaspc.empresa.posesiones.Computadora;
import ventaspc.empresa.posesiones.Producto;
import ventaspc.gui.modulos.PanelBase;

/**
 *
 * @author Ivan
 */
//Tabla únicamente para actualizar valores
public class RegistroComputadora_Editar extends PanelBase {
    private Producto p;
    private int pos;
    private JTable table;
    /**
     * Creates new form RegistroComputadora
     */
    public RegistroComputadora_Editar(Sistema sistema, Producto p, int pos, JTable table) {
        super(sistema);
        this.p = p;
        this.pos = pos;
        this.table = table;
        initComponents();
        establecerDatos();
    }
    
    public void limpiaDatos(){
        txtMarca.setText("");
        txtModelo.setText("");
        txtPrecio.setText("");
        txtClave.setText("");
        txtColor.setText("");
        txtProcesador.setText("");
        txtHdd.setText("");
        txtRam.setText("");
        txtVideo.setText("");
        txtAudio.setText("");
    }
    
    public void establecerDatos(){
        txtMarca.setText(p.getMarca());
        txtModelo.setText(p.getModelo());
        txtPrecio.setText(String.valueOf(p.getPrecio()));
        txtClave.setText(String.valueOf(p.getClave()));
        txtColor.setText(p.getColor());
        txtProcesador.setText(p.getProcesador());
        txtHdd.setText(String.valueOf(p.getHdd()));
        txtRam.setText(String.valueOf(p.getRam()));
        txtVideo.setText(p.getTarjetaVideo());
        txtAudio.setText(p.getTarjetaAudio());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtProcesador = new javax.swing.JTextField();
        txtHdd = new javax.swing.JTextField();
        txtVideo = new javax.swing.JTextField();
        txtAudio = new javax.swing.JTextField();
        btnGuardarComputadora = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtRam = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();

        jLabel1.setText("Marca:");

        jLabel2.setText("Modelo:");

        jLabel3.setText("Color:");

        jLabel4.setText("Procesador:");

        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("HDD (gb):");
        jLabel5.setToolTipText("Número entero únicamente");

        jLabel6.setText("Tarjeta de Video:");

        jLabel7.setText("Tarjeta de Audio:");

        txtVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVideoActionPerformed(evt);
            }
        });

        btnGuardarComputadora.setText("Actualizar");
        btnGuardarComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarComputadoraActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("RAM (gb):");
        jLabel8.setToolTipText("Número entero únicamente");

        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Precio:");
        jLabel9.setToolTipText("Cantidad con número");

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setText("Clave:");
        jLabel10.setToolTipText("Número entero únicamente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtHdd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtColor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRam)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardarComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnGuardarComputadora)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarComputadoraActionPerformed
        // TODO add your handling code here:
        String marca = txtMarca.getText();
        String modelo = txtModelo.getText();
        String color = txtColor.getText();
        String procesador = txtProcesador.getText();
        String video = txtVideo.getText();
        String audio = txtAudio.getText();
        
        
        if (marca.equals("") || modelo.equals("") || txtHdd.getText().equals("") || txtRam.getText().equals("") ||
        color.equals("") || procesador.equals("") || video.equals("") || audio.equals("")){
            JOptionPane.showInternalMessageDialog(this,"Hay campo(s) vacio(s)");
            return;
        }
        try{
            int clave = Integer.valueOf(txtClave.getText());
            int hdd = Integer.valueOf(txtHdd.getText());
            int ram = Integer.valueOf(txtRam.getText());
            double precio = Double.valueOf(txtPrecio.getText());

            Producto p = new Computadora(marca, modelo, color, precio, clave, procesador, ram, hdd, video, audio);
            if (sistema.getEmpresa().editarProducto(p,pos)){
                sistema.getGuardar().guardarProductos(sistema, null);
                actualizarTabla();
                table.revalidate();

                JOptionPane.showMessageDialog(this,"Actualizado");
                //limpiaDatos();
            }
            else{
                JOptionPane.showMessageDialog(this,"Esta clave le pertenece a otro producto");
            }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Número(s) inválido(s)");
            return;
        }
        
    }//GEN-LAST:event_btnGuardarComputadoraActionPerformed
    
    public void actualizarTabla(){
        table.setValueAt(txtMarca.getText(),pos,0);
        table.setValueAt(txtModelo.getText(),pos,1);
        table.setValueAt(txtColor.getText(),pos,2);
        table.setValueAt(txtPrecio.getText(),pos,3);
        table.setValueAt(txtClave.getText(),pos,4);
        table.setValueAt(txtProcesador.getText(),pos,5);
        table.setValueAt(txtRam.getText(),pos,6);
        table.setValueAt(txtHdd.getText(),pos,7);
        table.setValueAt(txtVideo.getText(),pos,8);
        table.setValueAt(txtAudio.getText(),pos,9);
    }
    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVideoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarComputadora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAudio;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtHdd;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProcesador;
    private javax.swing.JTextField txtRam;
    private javax.swing.JTextField txtVideo;
    // End of variables declaration//GEN-END:variables
}
