/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventaspc.gui;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ventaspc.empresa.posesiones.Cliente;
import ventaspc.empresa.posesiones.Computadora;
import ventaspc.LoginDialog;
import ventaspc.gui.modulos.PrincipalPanel;
import ventaspc.empresa.posesiones.Producto;
import ventaspc.empresa.posesiones.RegistroCompra;
import ventaspc.Sistema;
import ventaspc.gui.modulos.PanelBase;
/**
 *
 * @author Ivan
 */
public class VentanaPC extends javax.swing.JFrame {
    private Sistema sistema;
    
    public VentanaPC(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        setTitle("Ventas PC");
        setResizable(false);//Negar el reajuste de la ventana
        pack();
    }
    //Método para repintar la ventana
    public void mostrarPanel(PanelBase panel){
        panelContenido.removeAll();
        panelContenido.add(panel, BorderLayout.CENTER);
        panel.revalidate();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenido = new javax.swing.JPanel();
        bar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGuardarCambios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuProducto = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuVenta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuVerIngreso = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuExportarVentas = new javax.swing.JMenuItem();
        exportarCSVCliente = new javax.swing.JMenuItem();
        exportarCSVProductos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelContenido.setMinimumSize(new java.awt.Dimension(364, 385));
        panelContenido.setLayout(new java.awt.BorderLayout());

        jMenu1.setText("Archivo");

        menuGuardarCambios.setText("Guardar cambios");
        menuGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarCambiosActionPerformed(evt);
            }
        });
        jMenu1.add(menuGuardarCambios);
        jMenu1.add(jSeparator1);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        bar.add(jMenu1);

        jMenu4.setText("Opciones");

        jMenu5.setText("Cliente");

        menuCliente.setText("Editar/Buscar/Eliminar");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu5.add(menuCliente);

        jMenu4.add(jMenu5);

        jMenu6.setText("Producto");

        menuProducto.setText("Editar/Buscar/Eliminar");
        menuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductoActionPerformed(evt);
            }
        });
        jMenu6.add(menuProducto);

        jMenu4.add(jMenu6);

        jMenu7.setText("Venta");

        menuVenta.setText("Editar/Buscar/Eliminar");
        menuVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentaActionPerformed(evt);
            }
        });
        jMenu7.add(menuVenta);

        jMenu4.add(jMenu7);

        bar.add(jMenu4);

        jMenu2.setText("Herramientas");

        menuVerIngreso.setText("Ver ingreso de la empresa");
        menuVerIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerIngresoActionPerformed(evt);
            }
        });
        jMenu2.add(menuVerIngreso);

        jMenu8.setText("Exportar");

        menuExportarVentas.setText("Exportar CSV de ventas");
        menuExportarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExportarVentasActionPerformed(evt);
            }
        });
        jMenu8.add(menuExportarVentas);

        exportarCSVCliente.setText("Exportar CSV de clientes");
        exportarCSVCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarCSVClienteActionPerformed(evt);
            }
        });
        jMenu8.add(exportarCSVCliente);

        exportarCSVProductos.setText("Exportar CSV de productos");
        exportarCSVProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarCSVProductosActionPerformed(evt);
            }
        });
        jMenu8.add(exportarCSVProductos);

        jMenu2.add(jMenu8);

        bar.add(jMenu2);

        jMenu3.setText("Ayuda");

        menuAcercaDe.setText("Acerca de");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });
        jMenu3.add(menuAcercaDe);

        bar.add(jMenu3);

        setJMenuBar(bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(516, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Event-handlers para exportar. Se lanzan los métodos desde la clase Exportar.
    private void exportarCSVClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarCSVClienteActionPerformed
        // TODO add your handling code here:
        //Recibe como parámetros una referencia a Sistema y al panel de este JFrame
        sistema.getExportar().exportarCSVClientes(sistema, panelContenido);
    }//GEN-LAST:event_exportarCSVClienteActionPerformed

    private void exportarCSVProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarCSVProductosActionPerformed
        // TODO add your handling code here:
        sistema.getExportar().exportarCSVProductos(sistema, panelContenido);
    }//GEN-LAST:event_exportarCSVProductosActionPerformed

    private void menuVerIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerIngresoActionPerformed
        // TODO add your handling code here:
        try{
            JOptionPane.showMessageDialog(this,"Ingreso total de la empresa: $" + sistema.getEmpresa().getIngreso()
        + "\nNumero de ventas totales: " + sistema.getEmpresa().getNumVentas());
            //Se muestra el número de ventas y las ganancias totales que la empresa
            //ha tenido
        }
        catch(NullPointerException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuVerIngresoActionPerformed

    private void menuExportarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExportarVentasActionPerformed
        // TODO add your handling code here:
        sistema.getExportar().exportarVentas(sistema, panelContenido);
    }//GEN-LAST:event_menuExportarVentasActionPerformed

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Proyecto - Programación Orientada a Objetos\nEquipo:\nIván Soto\nChristian Villareal\nProfesor: Jorge Luis Peña Flores");
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);//Salir del programa
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarCambiosActionPerformed
        // TODO add your handling code here:
        //Opción del menú para guardar cualquier cambio realizado
        sistema.getGuardar().guardarClientes(sistema, panelContenido);
        sistema.getGuardar().guardarProductos(sistema, panelContenido);
        sistema.getGuardar().guardarVentas(sistema, panelContenido);
        sistema.getGuardar().guardarEmpleados(sistema, panelContenido);
    }//GEN-LAST:event_menuGuardarCambiosActionPerformed
    //Muestra de los páneles con las opciones de Editar, Eliminar, Buscar
    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_CLIENTESTABLA);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductoActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_COMPUTADORASTABLA);
    }//GEN-LAST:event_menuProductoActionPerformed

    private void menuVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentaActionPerformed
        // TODO add your handling code here:
        sistema.mostrarPanel(PanelBase.PANEL_VENTASTABLA);
    }//GEN-LAST:event_menuVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bar;
    private javax.swing.JMenuItem exportarCSVCliente;
    private javax.swing.JMenuItem exportarCSVProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuAcercaDe;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuExportarVentas;
    private javax.swing.JMenuItem menuGuardarCambios;
    private javax.swing.JMenuItem menuProducto;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuVenta;
    private javax.swing.JMenuItem menuVerIngreso;
    private javax.swing.JPanel panelContenido;
    // End of variables declaration//GEN-END:variables
}
